# Generated by Django 5.1.6 on 2025-03-03 13:43

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Expenses",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("date", models.DateTimeField(auto_now_add=True)),
                ("description", models.TextField()),
                ("credits", models.IntegerField(blank=True, default=0, null=True)),
                ("debit", models.IntegerField(blank=True, default=0, null=True)),
                ("balance", models.IntegerField(blank=True, null=True)),
            ],
        ),
    ]
